repo_url: https://github.com/jsquaredosquared/PyRegexBuilder

site_name: PyRegexBuilder
nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - API reference:
      - Common: api-reference/common.md
      - Assertions: api-reference/assertions.md
      - Character classes: api-reference/character-classes.md
      - Groups: api-reference/groups.md
      - Quantifiers: api-reference/quantifiers.md
  - Contributing: contributing.md
theme:
  name: material
  palette:
    scheme: slate
    primary: deep orange
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: deep orange
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.copy
  icon:
    repo: fontawesome/brands/github-alt

plugins:
  - search
  - mkdocstrings
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
