[project]
name = "regex-builder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.3.5",
    "regex>=2024.11.6",
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
